name: wdb106_sample
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.18.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation:
  gap:
  go_router:
  http:
  intl:
  meta:
  simple_logger:
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  go_router_builder:
  image_test_utils:
    git:
      url: https://github.com/michaelgobbers/image_test_utils
      ref: 6160ecc
  json_serializable:
  mocktail:
  pedantic_mono:
flutter:
  uses-material-design: true
